# Generated by Django 6.0.2 on 2026-06-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_lessoncompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Technology', 'Technology'), ('Business', 'Business'), ('Arts & Design', 'Arts & Design'), ('Health & Science', 'Health & Science'), ('Languages', 'Languages'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
